### ISSUE TITLE
dyndns no longer an option

### ISSUE THREAD

**Issue by SirKratosAurion** [workerforce/unifi-ddns#51] opened 2024-01-24 00:47 UTC
DynDNS is no longer a service listed in UDM PRO

**Comment by joealden** [comment] 2024-01-25 22:54
It looks like they've rebranded to just "dyn", so I presume that's what Ubiquiti has renamed it to. Am going to get this setup this weekend so will confirm if that works. Agree that it'd be good for the install guide to get updated though!

**Comment by joealden** [comment] 2024-01-25 23:05
Guess it depends what your goal is - I just got a email from Google domains that Squarespace won't support  DDNS when they migrate, and I already have other domains on Cloudflare, so don't want to introduce an extra failure point if possible!

**Comment by bsdkurt** [comment] 2024-01-25 23:26
> It looks like they've rebranded to just "dyn", so I presume that's what Ubiquiti has renamed it to. Am going to get this setup this weekend so will confirm if that works. Agree that it'd be good for the install guide to get updated though!

Yes, I can confirm that "dyn" is what "dyndns" was renamed to. I just tested a new entry using dyn and it worked fine.

**Comment by caniko** [comment] 2024-01-27 07:32
I have a protocol option on the EdgeRouter, and here I can pick between `dyndns1` and `dyndns2`. Which one is the correct one?

There is also `Web`, here I picked `dyndns`.

**Comment by willswire** [comment] 2024-02-19 14:00
closed via @bsdkurt's answer

**Closed by willswire** 2024-02-19 14:00 UTC

**Comment by caniko** [comment] 2024-02-19 16:11
Love that you answered my question @willswire :laughing:

The answer is, use `dyndns2`.
